language: node_js
node_js:
  - "lts/*"
install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

script:
  - node_modules/.bin/gatsby

after_success:
  - node_modules/.bin/gulp deploy --user $FTP_USER --password $FTP_PASSWORD
